# data
image_index_file: F:\Raccoon\train.txt
annot_encode_folder: F:\Raccoon\labels
save_file: F:\SaveModels\FasterRCNN\raccoon.pth
pre_train: False

labels: [ "raccoon"]
input_size: 800
anchor_base_size: 16
anchor_ratios: [ 0.5, 1, 2 ]
anchor_scales: [ 8, 16, 32 ]
# enhance
enhance: True
loc_normalize_mean: [ 0., 0., 0., 0. ]
loc_normalize_std: [ 0.1, 0.1, 0.2, 0.2 ]

# training
epoch: 100
batch_size: 8
learning_rate: 0.0001

val_split: 0.1

# loss
rpn_sigma: 3.
roi_sigma: 1.





